version: "3.8"
services:

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 192.168.1.21

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
